Update Locale_RU.yml
Zrips/CMI pull request #7449
Opened 2022-12-18 22:09 UTC by NONPLAYT

again some new ru translations

2022-12-19 17:06 UTC, NightNutSky requested changes
Почему ты удалил переводы в некоторых других строках?

2022-12-19 17:13 UTC, NightNutSky commented
> > Почему ты удалил переводы в некоторых других строках?
> 
> Нигде ничего не удалено, я удалял старые переводы и вводил новые 

Ты в этом точно уверен? 🤔
Например: 
![Screenshot_20221219-200831~2](https://user-images.githubusercontent.com/70456337/208481933-56884fb7-8988-496c-9fbd-b977534e5ec9.png)
![Screenshot_20221219-200915~2](https://user-images.githubusercontent.com/70456337/208481942-04c1178f-2f40-44a6-b20e-89fa7c1e2ab9.png)

2022-12-19 17:17 UTC, NightNutSky commented
> UPD: щас заметил, пофикшу
👌

2022-12-19 20:52 UTC, NightNutSky commented
По идее, эти строки же из статистики?
Не должны ли быть слова в другом падеже?
Аля вместо "Взаимодействие с кафедрой" - "Взаимодействий с кафедрой" (как было в предыдущем).

Пример: `Взаимодействий с кафедрой: 15`

Я бы мог проверить это в самой игре, но сейчас нет возможности зайти.

2022-12-20 19:31 UTC, NONPLAYT commented
очень странно, у меня почему то в форке все поломалось. все было на английском в начале и я перевёл. а оказывается что все было и так переведено

2022-12-20 19:34 UTC, closed without merging

2022-12-21 07:53 UTC, NightNutSky commented
> очень странно, у меня почему то в форке все поломалось. все было на английском в начале и я перевёл. а оказывается что все было и так переведено

Может, ты забыл синхронизировать его? Я недавно сделал перевод того, что было не переведено (и внёс лёгкие изменения в уже существующий, но не стал проверять на грамматические ошибки и так далее). Пулл - https://github.com/Zrips/CMI/pull/7430.